### ISSUE TITLE
How to access to the id of the parent?

### ISSUE THREAD

**Issue by alexisLefebvre** [neylsongularte/eloquent-extra-events#1]
In `BelongsToMany`, there is a [`parent_id`](https://github.com/neylsongularte/eloquent-extra-events/blob/5016bd170bbff10c420ee86814affee533975267/src/BelongsToMany.php#L63) but this data is never passed. Is it possible to pass this value to the events?

I would like to modify a model but I need its id in order to update it.

**Comment by alexisLefebvre** [comment]
Oops, I just saw that `parent_id` was already provided.

**Comment by neylsongularte** [comment]
:+1:
