### ISSUE TITLE
Integration with owen-it/laravel-auditing

### ISSUE THREAD

**Issue by eliseuborges** [neylsongularte/eloquent-extra-events#4]
Sua solução funciona com owen-it/laravel-auditing, ou seja, configurando seu pacote o owen-it/laravel-auditing irá capturar os eventos sync, attach e detach?

**Comment by neylsongularte** [comment]
o pacote owen-it/laravel-auditing não tem suporte pra isso ainda, existe uma issue aberta no projeto pra tentar resolver esse problema:
https://github.com/owen-it/laravel-auditing/issues/58

**Comment by neylsongularte** [comment]
nos comentários dessa issue eu descrevi minha solução temporária: https://github.com/owen-it/laravel-auditing/issues/58#issuecomment-300800530

**Comment by eliseuborges** [comment]
Então quer dizer que se eu inserir sua solução temporária no meu código a auditoria vai funcionar com sync, attach e detach?

**Comment by neylsongularte** [comment]
sim, dê uma olhada no código pra ver se resolve seu problema

**Comment by eliseuborges** [comment]
Em app/Providers/AppServiceProvider.php devo incluir o codigo dentro do metodo register ou boot?

**Comment by neylsongularte** [comment]
boot

**Comment by eliseuborges** [comment]
Estou recebendo uma mensagem de erro "Illegal string offset 'parent_id'". Devo criar esse atributo no meu modelo?

**Comment by eliseuborges** [comment]
Maravilha! Funcionou! Muito obrigado!
